version: "3.3"
services:
  oracledb:
    image: quay.io/migutak/oracledb-apis-lb4:1.0.0
    container_name: oracledb-dev
    restart: always
    environment:
      - DBHOST=172.16.20.2
      - DBPORT=1521
      - DBUSER=ecol
      - DBPASSWORD=DsQSnttm_1
      - DBDATABASE=ECOLTST
    ports:
      - "6001:6001"
